### ISSUE TITLE
clang trunk requires cl_khr_gl_msaa_sharing to be enabled before image2d_array_msaa_t can be used in the header file

### ISSUE THREAD

**Issue by aaronenyeshi** [KhronosGroup/SPIR#13] opened 2016-03-22 14:59 UTC
Command Line:
clang -cc1 -x cl -cl-std=CL2.0 -include C:\llvmspirv\llvm\tools\clang\lib\Headers/opencl-20.h -emit-llvm -triple spir64-unknown-unknown -o _temp_1_Tonga.clang.bc _temp_1_Tonga.i

Error Messages: 
In file included from <built-in>:303:
In file included from <command line>:1:
C:\llvmspirv\llvm\tools\clang\lib\Headers/opencl-20.h:3945:60: error: use of type 'image2d_msaa_t' requires cl_khr_gl_msaa_sharing extension to be enabled
float4 **attribute**((overloadable)) read_imagef(read_only image2d_msaa_t image, int2 coord, int sample);

Cause: clang trunk requires cl_khr_gl_msaa_sharing to be enabled before image2d_array_masaa_t can be used, in the header file.

Workaround: Enable this extension at the beginning of header file, and disable at the end.

**Comment by aaronenyeshi** [comment] 2016-03-22 15:04
This issue can be reproduced even with an empty kernel

**Comment by aaronenyeshi** [comment] 2016-03-22 18:11
Also a similar issue is:
error: use of type 'atomic_long' (aka '_Atomic(long)') requires cl_khr_int64_extended_atomics extension to be enabled

**Comment by bader** [comment] 2016-03-22 19:28
Thanks for reporting these issues. I'll try to fix them tomorrow.

**Comment by bader** [comment] 2016-03-23 13:09
The issue with cl_khr_gl_msaa_sharing extension should be fixed @ https://github.com/KhronosGroup/SPIR/commit/03a5e8866248b3cb112467a10e845ce995493530.

Unfortunately I can't reproduce the issue with atomic_long. I looked at the code and it looks good to me. Please, create another issue and attach a reproducer if you still have problems with it.

**Closed as completed by bader** 2016-03-23 13:09 UTC
