### ISSUE TITLE
llvm-spirv does not output optional literals in OpExecutionMode

### ISSUE THREAD

**Issue by ex-rzr** [KhronosGroup/SPIR#59] opened 2016-12-14 10:56 UTC
When **Execution Mode** is **SubgroupsPerWorkgroup** (36) it outputs
`4 ExecutionMode 4 36`
It should output: `4 ExecutionMode 4 36 <integer literal>`.
I haven't try all other Execution Modes, but it works correctly for **LocalSize**, **LocalSizeHint**, **VecTypeHint**.

(spirv-dis from SPIRV-Tools shows “OpExecutionMode %4 SubgroupsPerWorkgroup 12” as expected)

**Comment by bader** [comment] 2016-12-14 11:14
llvm-spirv tool is part of KhronosGroup/SPIRV-LLVM project.
There is already duplicate of this issue there: https://github.com/KhronosGroup/SPIRV-LLVM/issues/199.

**Comment by ex-rzr** [comment] 2016-12-14 11:15
Sorry for the mess. I've opened this report here: https://github.com/KhronosGroup/SPIRV-LLVM/issues/199

**Closed as completed by bader** 2016-12-14 11:14 UTC
